packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  electron-winstaller: set this to true or false
  esbuild: set this to true or false
onlyBuiltDependencies:
  - electron-winstaller
  - esbuild
  - node-pty
overrides:
  '@workloom/ui@0.1.1': https://cnb.cool/workloom-ai/workloom-im/-/releases/download/ui-v0.1.1/workloom-ui-0.1.1.tgz
